// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/issue-token": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "IssueToken - 토큰 발급 ✅",
                "parameters": [
                    {
                        "description": "토큰 발급 요청",
                        "name": "IssueTokenRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presenter.IssueTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "토큰 발급 성공",
                        "schema": {
                            "$ref": "#/definitions/presenter.IssueTokenResponse"
                        }
                    },
                    "404": {
                        "description": "사용자를 찾을 수 없음 : user not found",
                        "schema": {
                            "$ref": "#/definitions/errors.Error"
                        }
                    }
                }
            }
        },
        "/auth/validate": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Validate - 토큰 유효성 검사 ✅",
                "responses": {
                    "200": {
                        "description": "토큰 유효성 검사 성공",
                        "schema": {
                            "$ref": "#/definitions/presenter.ValidateResponse"
                        }
                    },
                    "404": {
                        "description": "사용자를 찾을 수 없음 : user not found",
                        "schema": {
                            "$ref": "#/definitions/errors.Error"
                        }
                    }
                }
            }
        },
        "/groups": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "List groups - 그룹 다건 조회 ✅",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presenter.ListGroupsResponse"
                        }
                    },
                    "404": {
                        "description": "그룹을 찾지 못함: group not found",
                        "schema": {
                            "$ref": "#/definitions/errors.Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Create a group - 그룹 단건 생성 및 참여 ✅",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "CreateGroupRequest",
                        "name": "CreateGroupRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presenter.CreateGroupRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/presenter.CreateGroupResponse"
                        }
                    }
                }
            }
        },
        "/groups/{group-id}": {
            "patch": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Patch a group - 그룹 단건 수정 ✅",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Group ID",
                        "name": "group-id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "PatchGroupRequest",
                        "name": "PatchGroupRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presenter.PatchGroupRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "그룹 소유자가 아님: group not owned",
                        "schema": {
                            "$ref": "#/definitions/errors.Error"
                        }
                    },
                    "404": {
                        "description": "그룹을 찾지 못함: group not found",
                        "schema": {
                            "$ref": "#/definitions/errors.Error"
                        }
                    }
                }
            }
        },
        "/groups/{group-id}/join": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Join a group - 그룹 단건 참여 ✅",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Group ID",
                        "name": "group-id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "그룹에 이미 참여함: group already joined",
                        "schema": {
                            "$ref": "#/definitions/errors.Error"
                        }
                    },
                    "404": {
                        "description": "그룹을 찾지 못함: group not found",
                        "schema": {
                            "$ref": "#/definitions/errors.Error"
                        }
                    }
                }
            }
        },
        "/groups/{group-id}/leave": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Leave a group - 그룹 단건 탈퇴 ✅",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Group ID",
                        "name": "group-id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "그룹 소유자가 아님: group not owned",
                        "schema": {
                            "$ref": "#/definitions/errors.Error"
                        }
                    },
                    "404": {
                        "description": "그룹을 찾지 못함: group not found",
                        "schema": {
                            "$ref": "#/definitions/errors.Error"
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "CreateUser - 사용자 단건 생성 ✅",
                "parameters": [
                    {
                        "description": "사용자 생성 요청",
                        "name": "CreateUserRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presenter.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "회원가입에 성공한 사용자 정보",
                        "schema": {
                            "$ref": "#/definitions/presenter.CreateUserResponse"
                        }
                    },
                    "409": {
                        "description": "사용자가 이미 존재함 : user already exists",
                        "schema": {
                            "$ref": "#/definitions/errors.Error"
                        }
                    }
                }
            }
        },
        "/users/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "FindUserByMe - 사용자(나) 단건 조회 ✅",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "내 정보 조회에 성공한 사용자 정보",
                        "schema": {
                            "$ref": "#/definitions/presenter.FindUserByMeResponse"
                        }
                    },
                    "404": {
                        "description": "유저를 찾지 못함: user not found",
                        "schema": {
                            "$ref": "#/definitions/errors.Error"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "DeleteUserByMe - 사용자(나) 단건 삭제 ✅",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "유저를 찾지 못함: user not found",
                        "schema": {
                            "$ref": "#/definitions/errors.Error"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "PatchUserByMe - 사용자(나) 단건 수정 ✅",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "사용자 수정 요청",
                        "name": "PatchUserByMeRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presenter.PatchUserByMeRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "유저를 찾지 못함: user not found",
                        "schema": {
                            "$ref": "#/definitions/errors.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "errors.Error": {
            "type": "object",
            "properties": {
                "detail": {
                    "description": "오류의 상세 설명",
                    "type": "string"
                },
                "instance": {
                    "description": "오류가 발생한 특정 인스턴스를 식별하는 데 사용할 수 있는 URI입니다.",
                    "type": "string"
                },
                "status": {
                    "description": "HTTP 상태 코드",
                    "type": "integer"
                },
                "title": {
                    "description": "오류의 짧은 제목",
                    "type": "string"
                }
            }
        },
        "presenter.CreateGroupRequest": {
            "type": "object",
            "properties": {
                "bookAuthor": {
                    "type": "string"
                },
                "bookIntroduction": {
                    "type": "string"
                },
                "bookPageCount": {
                    "type": "integer"
                },
                "bookPageMax": {
                    "type": "integer"
                },
                "bookPublisher": {
                    "type": "string"
                },
                "bookTitle": {
                    "type": "string"
                }
            }
        },
        "presenter.CreateGroupResponse": {
            "type": "object",
            "properties": {
                "bookAuthor": {
                    "type": "string"
                },
                "bookIntroduction": {
                    "type": "string"
                },
                "bookPageCount": {
                    "type": "integer"
                },
                "bookPageMax": {
                    "type": "integer"
                },
                "bookPublisher": {
                    "type": "string"
                },
                "bookTitle": {
                    "type": "string"
                }
            }
        },
        "presenter.CreateUserRequest": {
            "type": "object",
            "required": [
                "nickname"
            ],
            "properties": {
                "nickname": {
                    "type": "string"
                },
                "resolution": {
                    "type": "string"
                }
            }
        },
        "presenter.CreateUserResponse": {
            "type": "object",
            "properties": {
                "nickname": {
                    "type": "string"
                },
                "resolution": {
                    "type": "string"
                }
            }
        },
        "presenter.FindUserByMeResponse": {
            "type": "object",
            "properties": {
                "nickname": {
                    "type": "string"
                },
                "resolution": {
                    "type": "string"
                }
            }
        },
        "presenter.GroupsResponse": {
            "type": "object",
            "properties": {
                "bookAuthor": {
                    "type": "string"
                },
                "bookIntroduction": {
                    "type": "string"
                },
                "bookPageCount": {
                    "type": "integer"
                },
                "bookPageMax": {
                    "type": "integer"
                },
                "bookPublisher": {
                    "type": "string"
                },
                "bookTitle": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "presenter.IssueTokenRequest": {
            "type": "object",
            "properties": {
                "nickname": {
                    "type": "string"
                }
            }
        },
        "presenter.IssueTokenResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "presenter.ListGroupsResponse": {
            "type": "object",
            "properties": {
                "groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/presenter.GroupsResponse"
                    }
                }
            }
        },
        "presenter.PatchGroupRequest": {
            "type": "object",
            "properties": {
                "bookAuthor": {
                    "type": "string"
                },
                "bookIntroduction": {
                    "type": "string"
                },
                "bookPageCount": {
                    "type": "integer"
                },
                "bookPageMax": {
                    "type": "integer"
                },
                "bookPublisher": {
                    "type": "string"
                },
                "bookTitle": {
                    "type": "string"
                },
                "groupID": {
                    "type": "integer"
                }
            }
        },
        "presenter.PatchUserByMeRequest": {
            "type": "object",
            "properties": {
                "nickname": {
                    "type": "string"
                },
                "resolution": {
                    "type": "string"
                }
            }
        },
        "presenter.ValidateResponse": {
            "type": "object",
            "properties": {
                "nickname": {
                    "type": "string"
                },
                "resolution": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
