// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/users": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "CreateUser ✅",
                "responses": {
                    "201": {
                        "description": "회원가입에 성공한 사용자 정보",
                        "schema": {
                            "$ref": "#/definitions/presenter.CreateUserRequest"
                        }
                    }
                }
            }
        },
        "/users/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "FindUserByMe ✅",
                "responses": {
                    "200": {
                        "description": "내 정보 조회에 성공한 사용자 정보",
                        "schema": {
                            "$ref": "#/definitions/presenter.FindUserByMeResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "presenter.CreateUserRequest": {
            "type": "object",
            "required": [
                "nickname"
            ],
            "properties": {
                "nickname": {
                    "type": "string"
                },
                "resolution": {
                    "type": "string"
                }
            }
        },
        "presenter.FindUserByMeResponse": {
            "type": "object",
            "properties": {
                "nickname": {
                    "type": "string"
                },
                "resolution": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
