definitions:
  errors.Error:
    properties:
      detail:
        description: 오류의 상세 설명
        type: string
      instance:
        description: 오류가 발생한 특정 인스턴스를 식별하는 데 사용할 수 있는 URI입니다.
        type: string
      status:
        description: HTTP 상태 코드
        type: integer
      title:
        description: 오류의 짧은 제목
        type: string
    type: object
  presenter.CreateGroupRequest:
    properties:
      bookAuthor:
        type: string
      bookIntroduction:
        type: string
      bookPageCount:
        type: integer
      bookPageMax:
        type: integer
      bookPublisher:
        type: string
      bookTitle:
        type: string
    type: object
  presenter.CreateGroupResponse:
    properties:
      bookAuthor:
        type: string
      bookIntroduction:
        type: string
      bookPageCount:
        type: integer
      bookPageMax:
        type: integer
      bookPublisher:
        type: string
      bookTitle:
        type: string
    type: object
  presenter.CreateUserRequest:
    properties:
      nickname:
        type: string
      resolution:
        type: string
    required:
    - nickname
    type: object
  presenter.CreateUserResponse:
    properties:
      nickname:
        type: string
      resolution:
        type: string
    type: object
  presenter.FindUserByMeResponse:
    properties:
      nickname:
        type: string
      resolution:
        type: string
    type: object
  presenter.GroupsResponse:
    properties:
      bookAuthor:
        type: string
      bookIntroduction:
        type: string
      bookPageCount:
        type: integer
      bookPageMax:
        type: integer
      bookPublisher:
        type: string
      bookTitle:
        type: string
      id:
        type: integer
    type: object
  presenter.IssueTokenRequest:
    properties:
      nickname:
        type: string
    type: object
  presenter.IssueTokenResponse:
    properties:
      token:
        type: string
    type: object
  presenter.ListGroupsResponse:
    properties:
      groups:
        items:
          $ref: '#/definitions/presenter.GroupsResponse'
        type: array
    type: object
  presenter.PatchGroupRequest:
    properties:
      bookAuthor:
        type: string
      bookIntroduction:
        type: string
      bookPageCount:
        type: integer
      bookPageMax:
        type: integer
      bookPublisher:
        type: string
      bookTitle:
        type: string
      groupID:
        type: integer
    type: object
  presenter.PatchUserByMeRequest:
    properties:
      nickname:
        type: string
      resolution:
        type: string
    type: object
  presenter.ValidateResponse:
    properties:
      nickname:
        type: string
      resolution:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/issue-token:
    post:
      parameters:
      - description: 토큰 발급 요청
        in: body
        name: IssueTokenRequest
        required: true
        schema:
          $ref: '#/definitions/presenter.IssueTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 토큰 발급 성공
          schema:
            $ref: '#/definitions/presenter.IssueTokenResponse'
        "404":
          description: '사용자를 찾을 수 없음 : user not found'
          schema:
            $ref: '#/definitions/errors.Error'
      summary: IssueToken - 토큰 발급 ✅
      tags:
      - auth
  /auth/validate:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: 토큰 유효성 검사 성공
          schema:
            $ref: '#/definitions/presenter.ValidateResponse'
        "404":
          description: '사용자를 찾을 수 없음 : user not found'
          schema:
            $ref: '#/definitions/errors.Error'
      security:
      - BearerAuth: []
      summary: Validate - 토큰 유효성 검사 ✅
      tags:
      - auth
  /groups:
    get:
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presenter.ListGroupsResponse'
        "404":
          description: '그룹을 찾지 못함: group not found'
          schema:
            $ref: '#/definitions/errors.Error'
      security:
      - Bearer: []
      summary: List groups - 그룹 다건 조회 ✅
      tags:
      - groups
    post:
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: CreateGroupRequest
        in: body
        name: CreateGroupRequest
        required: true
        schema:
          $ref: '#/definitions/presenter.CreateGroupRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/presenter.CreateGroupResponse'
      security:
      - Bearer: []
      summary: Create a group - 그룹 단건 생성 및 참여 ✅
      tags:
      - groups
  /groups/{group-id}:
    patch:
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Group ID
        in: path
        name: group-id
        required: true
        type: string
      - description: PatchGroupRequest
        in: body
        name: PatchGroupRequest
        required: true
        schema:
          $ref: '#/definitions/presenter.PatchGroupRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "403":
          description: '그룹 소유자가 아님: group not owned'
          schema:
            $ref: '#/definitions/errors.Error'
        "404":
          description: '그룹을 찾지 못함: group not found'
          schema:
            $ref: '#/definitions/errors.Error'
      security:
      - Bearer: []
      summary: Patch a group - 그룹 단건 수정 ✅
      tags:
      - groups
  /groups/{group-id}/join:
    post:
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Group ID
        in: path
        name: group-id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "403":
          description: '그룹에 이미 참여함: group already joined'
          schema:
            $ref: '#/definitions/errors.Error'
        "404":
          description: '그룹을 찾지 못함: group not found'
          schema:
            $ref: '#/definitions/errors.Error'
      security:
      - Bearer: []
      summary: Join a group - 그룹 단건 참여 ✅
      tags:
      - groups
  /groups/{group-id}/leave:
    post:
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Group ID
        in: path
        name: group-id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "403":
          description: '그룹 소유자가 아님: group not owned'
          schema:
            $ref: '#/definitions/errors.Error'
        "404":
          description: '그룹을 찾지 못함: group not found'
          schema:
            $ref: '#/definitions/errors.Error'
      security:
      - Bearer: []
      summary: Leave a group - 그룹 단건 탈퇴 ✅
      tags:
      - groups
  /users:
    post:
      parameters:
      - description: 사용자 생성 요청
        in: body
        name: CreateUserRequest
        required: true
        schema:
          $ref: '#/definitions/presenter.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: 회원가입에 성공한 사용자 정보
          schema:
            $ref: '#/definitions/presenter.CreateUserResponse'
        "409":
          description: '사용자가 이미 존재함 : user already exists'
          schema:
            $ref: '#/definitions/errors.Error'
      security:
      - BearerAuth: []
      summary: CreateUser - 사용자 단건 생성 ✅
      tags:
      - users
  /users/me:
    delete:
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: '유저를 찾지 못함: user not found'
          schema:
            $ref: '#/definitions/errors.Error'
      security:
      - BearerAuth: []
      summary: DeleteUserByMe - 사용자(나) 단건 삭제 ✅
      tags:
      - users
    get:
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 내 정보 조회에 성공한 사용자 정보
          schema:
            $ref: '#/definitions/presenter.FindUserByMeResponse'
        "404":
          description: '유저를 찾지 못함: user not found'
          schema:
            $ref: '#/definitions/errors.Error'
      security:
      - BearerAuth: []
      summary: FindUserByMe - 사용자(나) 단건 조회 ✅
      tags:
      - users
    patch:
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 사용자 수정 요청
        in: body
        name: PatchUserByMeRequest
        required: true
        schema:
          $ref: '#/definitions/presenter.PatchUserByMeRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: '유저를 찾지 못함: user not found'
          schema:
            $ref: '#/definitions/errors.Error'
      security:
      - BearerAuth: []
      summary: PatchUserByMe - 사용자(나) 단건 수정 ✅
      tags:
      - users
swagger: "2.0"
